name: Autograding
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout alumno
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar
        run: javac -d out src/core/*.java src/solution/*.java

      - name: Descargar Tests Privados
        env:
          TOKEN: ${{ secrets.MY_PRIVATE_TOKEN }}
        run: |
          git clone https://x-access-token:$TOKEN@github.com/DAM-IES-La-Arboleda/bin-packing-private-tests.git secretos

      - name: Evaluar y generar nota
        id: grading
        run: |
          output=$(java -cp out core.Main secretos/data/private)
          echo "$output"

          score=$(echo "$output" | grep "PUNTUACIÓN MEDIA FINAL" | sed -E 's/.*: ([0-9.]+).*/\1/')

          echo "Final score: $score"

          # Convertir a entero (Classroom a veces lo requiere)
          score_int=$(printf "%.0f" $score)

          echo "SCORE=$score_int" >> $GITHUB_ENV