name: Update Leaderboard from Dispatch

on:
  repository_dispatch:
    types: [update_leaderboard]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar jq
        run: sudo apt-get install -y jq

      - name: Actualizar leaderboard
        run: |
          USER="${{ github.event.client_payload.user }}"
          SCORE="${{ github.event.client_payload.score }}"

          echo "Usuario: $USER"
          echo "Score: $SCORE"

          if [ ! -f leaderboard.json ]; then
            echo "{}" > leaderboard.json
          fi

          jq --arg user "$USER" --argjson score "$SCORE" \
            '.[$user] = ($score | tonumber)' leaderboard.json > tmp.json && mv tmp.json leaderboard.json

      - name: Commit cambios
        env:
          TOKEN: ${{ secrets.MY_PRIVATE_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git remote set-url origin https://x-access-token:$TOKEN@github.com/DAM-IES-La-Arboleda/bin-packing-template.git

          git add leaderboard.json
          git commit -m "Update leaderboard from $USER" || echo "No changes"

          git pull --rebase
          git push https://x-access-token:$TOKEN@github.com/DAM-IES-La-Arboleda/bin-packing-template.git